LOC = [
   "Ideas Hall",
   "Decisions HQ",
   "The Conference Space",
   "Kickstart Meetings",
   "Leaders Think Space",
   "Banding Together",
   "The Capital City",
   "Chromatic Commons",
   "Collective IQ",
   "Convening Space",
   "Cranium Focus",
   "Creative Arena",
   "Crowd Pleaser",
   "Crucial Conference",
   "Edge Conference",
   "Energy Boost",
   "Engagement Center",
   "Fellowship Hall",
   "Gathering Place",
   "Gig Gallery",
   "The Steam Room",
   "Alpha Room",
   "All Arrears",
   "Assembly Hall",
   "Away Bleachers",
   "Banding Together",
   "The Batcave",
   "Be Biggie",
   "Boardroom Bebop",
   "Bookworm badge",
   "Bored Room",
   "Break Up Room",
   "Bromance Chamber",
   "Carnegie Room",
   "Chromatic Commons",
   "Collective IQ Room",
   "Community Spot",
   "Convening Space",
   "Cranium Focus",
   "Creative Arena",
   "Crowd Pleaser",
   "Crown Down",
   "Dakota Room",
   "Dam Square",
   "Death Star",
   "Decision Accelerator",
   "Disappointment Beach",
   "Dragonstone",
   "Engagement Center",
   "Executive Playground",
   "Fellowship Hall",
   "Mens Toilet",
   "Womens Toilet",
   "Utility",
   "First World Problems",
   "Flatiron Room",
   "Gathering Field",
   "Gathering Place",
   "Germination Potential",
   "Gig Gallery",
   "Classic Talk",
   "Designated Area",
   "Organizational Space",
   "Local Landmarks",
   "Digital Signage",
   "Amber",
   "Entire Company",
   "Strategic Thought",
   "Traditional Approach",
   "Meeting Spaces",
   "Office Space",
   "Ginsberg",
   "City Hall",
   "City Lights",
   "Fourth Floor",
   "Fifth Floor",
   "First Floor",
   "Second Floor",
   "Fourth Floor",
   "Fifteenth Floor",
   "Tenth Floor",
   "Seventy Second Floor",
   "Office Culture",
   "Core Values",
   "Learning Space",
   "Art Director",
   "Page One",
   "Modern Workspace",
   "Interactive Wayfinding",
   "Potential Themes",
   "Space Utilization",
   "Space Travel",
   "Tech Leaders"
]
