TRADES = {
  "ac": "Air conditioning",
  "bc" : "Building control",
  "bp": "Building performance",
  "bsc": "Building services construction",
  "br": "Building Regulations",
  "cert" : "Certification",
  "dcom": "Decommissioning",
  "ee" : "Electrical Engineering",
  "es" : "Electrical Services",
  "ea" : "Energy audit",
  "em" : "Energy Management",
  "env" : "Environment",
  "et" : "Events & training",
  "fc" : "Facades",
  "fm" : "Facilities management",
  "fan" : "Fans",
  "fire" : "Fire",
  "gi" : "Green infrastructure",
  "hvac" : "Heating, Ventilation and Air Conditioning",
  "ht" : "Heritage",
  "itc" : "IT & controls",
  "lift" : "Lifts",
  "li" : "Lighting",
  "lev" : "Local Exhaust ventilation",
  "me" : "Mechanical Engineering",
  "ms" : "Modelling & simulation",
  "nv" : "Natural ventilation",
  "oe" : "Operational engineering",
  "pm" : "Project Management",
  "ph" : "Public health",
  "rf" : "Refrigeration",
  "snv" : "Sound/noise/vibration",
  "sv" : "Sustainability & Ventilation",
  "dhc" : "Decarbonising Heat and Cooling / Energy Storage",
  "moc" : "Modular and Off-site construction",
  "dig" : "Digitalisation",
  "pcs" : "People, Competence and Skills",
  "ci" : "Climate Impact",
  "rnr" : "Retrofit and Refurbishment",
  "hw" : "Health and Wellbeing"
}
print(len(TRADES))
