# Generated by Django 4.0.3 on 2022-04-26 00:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroups',
            fields=[
                ('accessGroup_id', models.AutoField(primary_key=True, serialize=False)),
                ('groupCode', models.CharField(max_length=6)),
                ('groupName', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['groupCode'],
            },
        ),
        migrations.CreateModel(
            name='BIM',
            fields=[
                ('bim_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('mongoDB_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BIMM',
            fields=[
                ('bimm_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('purchaseDate', models.DateTimeField(blank=True, null=True, verbose_name='Purchase Date')),
                ('warranty', models.BigIntegerField(blank=True, null=True, verbose_name='Warranty Documents')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('mtbf', models.IntegerField(blank=True, null=True, verbose_name='MTBF (in hours)')),
                ('hoursToDate', models.IntegerField(blank=True, null=True)),
                ('safety', models.BigIntegerField(blank=True, null=True, verbose_name='Safety Documentation')),
                ('manual', models.BigIntegerField(blank=True, null=True, verbose_name='Operating Manual')),
                ('msds', models.BigIntegerField(blank=True, null=True, verbose_name='MSDS')),
                ('iotURL', models.CharField(blank=True, max_length=255, null=True)),
                ('iotDevice', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewedDate', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed Date')),
                ('bim', models.ManyToManyField(to='ppt.bim')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BIMMbyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateModified', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('bimm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ppt.bimm')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('tradeName', models.CharField(max_length=255, verbose_name='Company Name')),
                ('compName', models.CharField(max_length=255, verbose_name='Trade Name')),
                ('abn', models.CharField(max_length=8, verbose_name='ABN')),
                ('account', models.CharField(default='999-999-9999', max_length=12, verbose_name='G/L account number')),
            ],
        ),
        migrations.CreateModel(
            name='CostCentre',
            fields=[
                ('costCentre_id', models.AutoField(primary_key=True, serialize=False)),
                ('costName', models.CharField(max_length=255, verbose_name='Cost Centre')),
                ('costAccount', models.CharField(default='999-999-9999', max_length=12, verbose_name='G/L account number')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ppt.company')),
            ],
            options={
                'ordering': ['costName'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('locationCode', models.CharField(max_length=26)),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('bimmbyloc', models.ManyToManyField(through='ppt.BIMMbyLocation', to='ppt.bimm')),
                ('costCentre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppt.costcentre')),
            ],
            options={
                'ordering': ['costCentre', 'locationCode'],
            },
        ),
        migrations.CreateModel(
            name='Nominal',
            fields=[
                ('nominal_id', models.AutoField(primary_key=True, serialize=False)),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dateBirth', models.DateTimeField(blank=True, null=True, verbose_name='Date of birth')),
                ('lastName', models.CharField(max_length=255, verbose_name='Last Name')),
                ('firstName', models.CharField(max_length=255, verbose_name='First Name')),
                ('middleName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Name')),
                ('driverLicense', models.IntegerField(blank=True, null=True, verbose_name='Driver License')),
                ('driverClass', models.CharField(default='C', max_length=4, verbose_name='Class of License')),
                ('address1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 1')),
                ('address2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('safety', models.BigIntegerField(blank=True, null=True, verbose_name='Safety Documentation')),
                ('incident', models.BigIntegerField(blank=True, null=True, verbose_name='Incident Documentation')),
                ('costCentre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ppt.costcentre')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal', verbose_name='Created By')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ppt.location')),
            ],
            options={
                'ordering': ['lastName'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('services_id', models.AutoField(primary_key=True, serialize=False)),
                ('serviceCode', models.CharField(max_length=6)),
                ('serviceName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='serviceLog',
            fields=[
                ('serviceLog_id', models.AutoField(primary_key=True, serialize=False)),
                ('logDate', models.DateTimeField()),
                ('note', models.TextField()),
                ('bimm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ppt.bimm')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ppt.nominal')),
            ],
        ),
        migrations.CreateModel(
            name='NominalGroupAccess',
            fields=[
                ('nominalGroupAccess_id', models.AutoField(primary_key=True, serialize=False)),
                ('accessGroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.accessgroups')),
                ('nominal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal')),
            ],
            options={
                'ordering': ['nominal'],
            },
        ),
        migrations.CreateModel(
            name='LocationGroupAccess',
            fields=[
                ('locationGroupAccess_id', models.AutoField(primary_key=True, serialize=False)),
                ('accessGroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.accessgroups')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.location')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('mongoDB_id', models.BigIntegerField(blank=True, null=True)),
                ('docName', models.CharField(max_length=255, verbose_name='name of document')),
                ('docDesc', models.TextField(blank=True, null=True)),
                ('nominal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppt.nominal')),
            ],
            options={
                'ordering': ['nominal', 'docName'],
            },
        ),
        migrations.AddField(
            model_name='costcentre',
            name='contactL1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal', verbose_name='Level 1 Contact'),
        ),
        migrations.AddField(
            model_name='costcentre',
            name='contactL2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal', verbose_name='Level 2 Contact'),
        ),
        migrations.AddField(
            model_name='costcentre',
            name='contactL3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal', verbose_name='Level 3 Contact'),
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('contractor_id', models.AutoField(primary_key=True, serialize=False)),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateModified', models.DateTimeField(default=django.utils.timezone.now)),
                ('companyName', models.CharField(max_length=255, verbose_name='Company Name')),
                ('companyNumber', models.CharField(default='999-9999', max_length=8, verbose_name='Company number')),
                ('companyPhone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('contactL1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal', verbose_name='Level 1 Contact')),
                ('contactL2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal', verbose_name='Level 2 Contact')),
                ('contactL3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal', verbose_name='Level 3 Contact')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ppt.services')),
            ],
            options={
                'ordering': ['companyName'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='contactL1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal', verbose_name='Level 1 Contact'),
        ),
        migrations.AddField(
            model_name='company',
            name='contactL2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal', verbose_name='Level 2 Contact'),
        ),
        migrations.AddField(
            model_name='company',
            name='contactL3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal', verbose_name='Level 3 Contact'),
        ),
        migrations.AddField(
            model_name='bimmbylocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ppt.location'),
        ),
        migrations.AddField(
            model_name='bimm',
            name='reviewedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal', verbose_name='Reviewed By'),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('nominal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ppt.nominal')),
                ('companyName', models.CharField(max_length=255)),
                ('services', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ppt.services')),
            ],
            bases=('ppt.nominal',),
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('nominal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ppt.nominal')),
                ('dateStart', models.DateTimeField(default=django.utils.timezone.now, verbose_name='job/contract start date')),
                ('dateModified', models.DateTimeField(default=django.utils.timezone.now)),
                ('contractor_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ppt.contractor')),
                ('services_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ppt.services')),
            ],
            options={
                'ordering': ['dateStart'],
            },
            bases=('ppt.nominal',),
        ),
    ]
