# Generated by Django 4.0.2 on 2022-03-19 03:26

import address.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0004_alter_address_id_alter_country_id_alter_locality_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroups',
            fields=[
                ('accessGroup_id', models.AutoField(primary_key=True, serialize=False)),
                ('groupCode', models.CharField(max_length=6)),
                ('groupName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BIM',
            fields=[
                ('bim_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BIMM',
            fields=[
                ('bimm_id', models.AutoField(primary_key=True, serialize=False)),
                ('bim', models.ManyToManyField(to='ppt.BIM')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('tradeName', models.CharField(max_length=255, verbose_name='Company Name')),
                ('compName', models.CharField(max_length=255, verbose_name='Trade Name')),
                ('abn', models.CharField(max_length=8, verbose_name='ABN')),
                ('account', models.CharField(default='999-999-9999', max_length=12, verbose_name='G/L account number')),
            ],
        ),
        migrations.CreateModel(
            name='CostCentre',
            fields=[
                ('costCentre_id', models.AutoField(primary_key=True, serialize=False)),
                ('costName', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ppt.company')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('locationCode', models.CharField(max_length=26)),
                ('bimm', models.ManyToManyField(to='ppt.BIMM')),
                ('costCentre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppt.costcentre')),
            ],
        ),
        migrations.CreateModel(
            name='Nominal',
            fields=[
                ('nominal_id', models.AutoField(primary_key=True, serialize=False)),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateBirth', models.DateTimeField(verbose_name='date of birth')),
                ('lastName', models.CharField(max_length=255, verbose_name='last name')),
                ('firstName', models.CharField(max_length=255, verbose_name='first name')),
                ('middleName', models.CharField(max_length=255, null=True, verbose_name='middle name')),
                ('driverLicense', models.IntegerField(null=True, verbose_name='driver license')),
                ('driverClass', models.CharField(default='C', max_length=4, verbose_name='class of license')),
                ('address1', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('address2', address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='address.address')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ppt.location')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('services_id', models.AutoField(primary_key=True, serialize=False)),
                ('serviceCode', models.CharField(max_length=6)),
                ('serviceName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NominalGroupAccess',
            fields=[
                ('nominalGroupAccess_id', models.AutoField(primary_key=True, serialize=False)),
                ('accessGroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.accessgroups')),
                ('nominal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal')),
            ],
        ),
        migrations.CreateModel(
            name='LocationGroupAccess',
            fields=[
                ('locationGroupAccess_id', models.AutoField(primary_key=True, serialize=False)),
                ('accessGroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.accessgroups')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.location')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('docName', models.CharField(max_length=255, verbose_name='name of document')),
                ('nominal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppt.nominal')),
            ],
        ),
        migrations.AddField(
            model_name='costcentre',
            name='contactL1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal'),
        ),
        migrations.AddField(
            model_name='costcentre',
            name='contactL2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal'),
        ),
        migrations.AddField(
            model_name='costcentre',
            name='contactL3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal'),
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('contractor_id', models.AutoField(primary_key=True, serialize=False)),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateModified', models.DateTimeField(default=django.utils.timezone.now)),
                ('companyName', models.CharField(max_length=255)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ppt.services')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='contactL1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal', verbose_name='Level 1 Contact'),
        ),
        migrations.AddField(
            model_name='company',
            name='contactL2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal', verbose_name='Level 2 Contact'),
        ),
        migrations.AddField(
            model_name='company',
            name='contactL3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal', verbose_name='Level 3 Contact'),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('nominal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ppt.nominal')),
                ('companyName', models.CharField(max_length=255)),
                ('services', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ppt.services')),
            ],
            bases=('ppt.nominal',),
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('nominal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ppt.nominal')),
                ('dateStart', models.DateTimeField(default=django.utils.timezone.now, verbose_name='job/contract start date')),
                ('dateModified', models.DateTimeField(default=django.utils.timezone.now)),
                ('contractor_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ppt.contractor')),
                ('services_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ppt.services')),
            ],
            bases=('ppt.nominal',),
        ),
    ]
