# Generated by Django 4.0.2 on 2022-03-19 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='companyNumber',
            field=models.CharField(default='999-9999', max_length=8, verbose_name='Company number'),
        ),
        migrations.AddField(
            model_name='costcentre',
            name='costAccount',
            field=models.CharField(default='999-999-9999', max_length=12, verbose_name='G/L account number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contactL1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal', verbose_name='Level 1 Contact'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contactL2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal', verbose_name='Level 2 Contact'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contactL3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal', verbose_name='Level 3 Contact'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='companyName',
            field=models.CharField(max_length=255, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='costcentre',
            name='contactL1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal'),
        ),
        migrations.AlterField(
            model_name='costcentre',
            name='contactL2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal'),
        ),
        migrations.AlterField(
            model_name='costcentre',
            name='contactL3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal'),
        ),
        migrations.AlterField(
            model_name='costcentre',
            name='costName',
            field=models.CharField(max_length=255, verbose_name='Cost Centre'),
        ),
        migrations.AlterField(
            model_name='nominal',
            name='middleName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='middle name'),
        ),
    ]
