# Generated by Django 4.0.3 on 2022-04-26 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominal',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='nominal',
            name='address2',
        ),
    ]
