# Generated by Django 4.0.3 on 2022-04-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0002_remove_nominal_address1_remove_nominal_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominal',
            name='address1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='nominal',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2'),
        ),
    ]
