# Generated by Django 4.0.2 on 2022-03-19 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0002_contractor_companynumber_costcentre_costaccount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessgroups',
            options={'ordering': ['groupCode']},
        ),
        migrations.AlterModelOptions(
            name='bim',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='bimm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='contractor',
            options={'ordering': ['companyName']},
        ),
        migrations.AlterModelOptions(
            name='costcentre',
            options={'ordering': ['costName']},
        ),
        migrations.AlterModelOptions(
            name='documents',
            options={'ordering': ['nominal', 'docName']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['costCentre', 'locationCode']},
        ),
        migrations.AlterModelOptions(
            name='nominalgroupaccess',
            options={'ordering': ['nominal']},
        ),
        migrations.AlterModelOptions(
            name='personnel',
            options={'ordering': ['dateStart']},
        ),
        migrations.AddField(
            model_name='bim',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bim',
            name='mongoDB_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bimm',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bimm',
            name='name',
            field=models.CharField(default='default', max_length=255, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='documents',
            name='docDesc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='mongoDB_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='costcentre',
            name='contactL1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal', verbose_name='Level 1 Contact'),
        ),
        migrations.AlterField(
            model_name='costcentre',
            name='contactL2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal', verbose_name='Level 2 Contact'),
        ),
        migrations.AlterField(
            model_name='costcentre',
            name='contactL3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ppt.nominal', verbose_name='Level 3 Contact'),
        ),
    ]
