# Generated by Django 4.0.3 on 2022-04-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0003_nominal_address1_nominal_address2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bim',
            name='mongoDB_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='bimm',
            name='manual',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Operating Manual'),
        ),
        migrations.AlterField(
            model_name='bimm',
            name='msds',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='MSDS'),
        ),
        migrations.AlterField(
            model_name='bimm',
            name='safety',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Safety Documentation'),
        ),
        migrations.AlterField(
            model_name='bimm',
            name='warranty',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Warranty Documents'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='mongoDB_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='nominal',
            name='incident',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Incident Documentation'),
        ),
        migrations.AlterField(
            model_name='nominal',
            name='safety',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Safety Documentation'),
        ),
    ]
