# Generated by Django 4.0.3 on 2022-04-26 04:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0004_alter_bim_mongodb_id_alter_bimm_manual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BIMMbyBIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateModified', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('bim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ppt.bim')),
            ],
        ),
        migrations.RemoveField(
            model_name='bimm',
            name='bim',
        ),
        migrations.AddField(
            model_name='bimm',
            name='bimmbyBIM',
            field=models.ManyToManyField(through='ppt.BIMMbyBIM', to='ppt.bim'),
        ),
        migrations.AddField(
            model_name='bimmbybim',
            name='bimm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ppt.bimm'),
        ),
    ]
