# Generated by Django 4.0.2 on 2022-03-19 09:21

import address.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_alter_address_id_alter_country_id_alter_locality_id_and_more'),
        ('ppt', '0004_location_description_nominal_costcentre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominal',
            name='address1',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
        migrations.AlterField(
            model_name='nominal',
            name='dateBirth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='nominal',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='nominal',
            name='driverLicense',
            field=models.IntegerField(blank=True, null=True, verbose_name='driver license'),
        ),
    ]
