# Generated by Django 4.0.3 on 2022-04-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0005_bimmbybim_remove_bimm_bim_bimm_bimmbybim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessgroups',
            name='accessLevel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
