# Generated by Django 4.0.3 on 2022-03-25 04:17

import address.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_alter_address_id_alter_country_id_alter_locality_id_and_more'),
        ('ppt', '0005_alter_nominal_address1_alter_nominal_datebirth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nominal',
            options={'ordering': ['lastName']},
        ),
        migrations.RenameField(
            model_name='location',
            old_name='bimm',
            new_name='bimmbyloc',
        ),
        migrations.AddField(
            model_name='bimm',
            name='purchaseDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bimm',
            name='warranty',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nominal',
            name='address1',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address', verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='nominal',
            name='dateBirth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='nominal',
            name='driverClass',
            field=models.CharField(default='C', max_length=4, verbose_name='Class of License'),
        ),
        migrations.AlterField(
            model_name='nominal',
            name='driverLicense',
            field=models.IntegerField(blank=True, null=True, verbose_name='Driver License'),
        ),
        migrations.AlterField(
            model_name='nominal',
            name='firstName',
            field=models.CharField(max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='nominal',
            name='lastName',
            field=models.CharField(max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='nominal',
            name='middleName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Name'),
        ),
        migrations.CreateModel(
            name='serviceLog',
            fields=[
                ('serviceLog_id', models.AutoField(primary_key=True, serialize=False)),
                ('logDate', models.DateTimeField()),
                ('note', models.TextField()),
                ('bimm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ppt.bimm')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ppt.nominal')),
            ],
        ),
        migrations.CreateModel(
            name='BIMMbyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateModified', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('bimm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ppt.bimm')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ppt.location')),
            ],
        ),
        migrations.CreateModel(
            name='ppt_location_bimm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ppt.bimm')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ppt.location')),
            ],
        ),    
    ]
