# Generated by Django 4.0.3 on 2022-03-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
       ('ppt', '0006_alter_nominal_options_rename_bimm_location_bimmbyloc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='bimmbyloc',
            field=models.ManyToManyField(through='ppt.BIMMbyLocation', to='ppt.bimm'),
        ),
        migrations.AddField(
            model_name='location',
            name='bimm',
            field=models.ManyToManyField(related_name='locations', through='ppt.BIMMbyLocation', to='ppt.bimm'),
        ),
#
#       migrations.DeleteModel(
#           name='ppt.ppt_location_bimm',
#       ),
#
    ]
