# Generated by Django 4.0.3 on 2022-04-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0007_rename_contractor_id_personnel_contractor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='percentage1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Percentage1'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='percentage2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Percentage2'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='percentage3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Percentage3'),
        ),
    ]
