# Generated by Django 4.0.4 on 2022-04-28 14:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0010_rename_mongodb_id_documents_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='companyPhone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Contact number'),
        ),
        migrations.AlterField(
            model_name='nominal',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Mobile number'),
        ),
        migrations.AlterField(
            model_name='nominal',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Contact phone number'),
        ),
    ]
